---
- name: Ansible Vault Test Playbook
  hosts: localhost
  vars_files:
    - secrets.yaml
  tasks:
    - name: Task 1 - Display User
      ansible.builtin.debug:
        msg: "The database user is {{ myuser }}"

    - name: Task 2 - Display Password
      ansible.builtin.debug:
        msg: "The database password is {{ mypasswd }}"
