---
- name: All-in-One Variable Preference Study with Roles
  hosts: localhost
  connection: local

  # 1. రోల్‌ని ఇక్కడ ఇంక్లూడ్ చేయాలి
  roles:
    - test_role

  # 5. Play Level
  vars:
    MY_VAR: "MY_VAR at Play Level"

  # 3. File Level
  vars_files:
    - variables.yaml

  # 4. Prompt Level
  vars_prompt:
    - name: "MY_VAR"
      prompt: "Please enter MY_VAR for Prompt Level"
      private: false

  tasks:
    - name: "Checking who wins the preference war"
      ansible.builtin.debug:
        msg: "The Winner is: {{ MY_VAR }}"
      
      # 2. Task Level
      vars:
        MY_VAR: "MY_VAR at Task Level"