[localhost]
3.218.67.93
#localhost MY_VAR="MY_VAR at Inventory Level"

[localhost:vars]
Course="DevOps From inventory"
Trainer="Chandrasekhar"
Duration="50HRS"
PERSON="chandra from inventory"
WISHES="HappyMorning from inventory"

